apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
  namespace: keycloak
spec:
  secretName: cloudflare-api-key-secret
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - keycloak.myeks.techwithpratik.tech