apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-cert
  namespace: utilities
spec:
  secretName: cloudflare-api-key-secret
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - argo.myeks.techwithpratik.tech